// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.6.1
// source: export.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExportType int32

const (
	ExportType_FULL_EXPORT      ExportType = 0
	ExportType_SELECTED_COLUMNS ExportType = 1
)

// Enum value maps for ExportType.
var (
	ExportType_name = map[int32]string{
		0: "FULL_EXPORT",
		1: "SELECTED_COLUMNS",
	}
	ExportType_value = map[string]int32{
		"FULL_EXPORT":      0,
		"SELECTED_COLUMNS": 1,
	}
)

func (x ExportType) Enum() *ExportType {
	p := new(ExportType)
	*p = x
	return p
}

func (x ExportType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExportType) Descriptor() protoreflect.EnumDescriptor {
	return file_export_proto_enumTypes[0].Descriptor()
}

func (ExportType) Type() protoreflect.EnumType {
	return &file_export_proto_enumTypes[0]
}

func (x ExportType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExportType.Descriptor instead.
func (ExportType) EnumDescriptor() ([]byte, []int) {
	return file_export_proto_rawDescGZIP(), []int{0}
}

type ExportAssetsRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AssetIds        []string               `protobuf:"bytes,1,rep,name=asset_ids,json=assetIds,proto3" json:"asset_ids,omitempty"`
	ExportType      ExportType             `protobuf:"varint,2,opt,name=export_type,json=exportType,proto3,enum=ExportType" json:"export_type,omitempty"`
	SelectedColumns []string               `protobuf:"bytes,3,rep,name=selected_columns,json=selectedColumns,proto3" json:"selected_columns,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ExportAssetsRequest) Reset() {
	*x = ExportAssetsRequest{}
	mi := &file_export_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportAssetsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportAssetsRequest) ProtoMessage() {}

func (x *ExportAssetsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_export_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportAssetsRequest.ProtoReflect.Descriptor instead.
func (*ExportAssetsRequest) Descriptor() ([]byte, []int) {
	return file_export_proto_rawDescGZIP(), []int{0}
}

func (x *ExportAssetsRequest) GetAssetIds() []string {
	if x != nil {
		return x.AssetIds
	}
	return nil
}

func (x *ExportAssetsRequest) GetExportType() ExportType {
	if x != nil {
		return x.ExportType
	}
	return ExportType_FULL_EXPORT
}

func (x *ExportAssetsRequest) GetSelectedColumns() []string {
	if x != nil {
		return x.SelectedColumns
	}
	return nil
}

type ExportJobDiffRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []int64                `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportJobDiffRequest) Reset() {
	*x = ExportJobDiffRequest{}
	mi := &file_export_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportJobDiffRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportJobDiffRequest) ProtoMessage() {}

func (x *ExportJobDiffRequest) ProtoReflect() protoreflect.Message {
	mi := &file_export_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportJobDiffRequest.ProtoReflect.Descriptor instead.
func (*ExportJobDiffRequest) Descriptor() ([]byte, []int) {
	return file_export_proto_rawDescGZIP(), []int{1}
}

func (x *ExportJobDiffRequest) GetIds() []int64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

var File_export_proto protoreflect.FileDescriptor

const file_export_proto_rawDesc = "" +
	"\n" +
	"\fexport.proto\"\x8b\x01\n" +
	"\x13ExportAssetsRequest\x12\x1b\n" +
	"\tasset_ids\x18\x01 \x03(\tR\bassetIds\x12,\n" +
	"\vexport_type\x18\x02 \x01(\x0e2\v.ExportTypeR\n" +
	"exportType\x12)\n" +
	"\x10selected_columns\x18\x03 \x03(\tR\x0fselectedColumns\"(\n" +
	"\x14ExportJobDiffRequest\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\x03R\x03ids*3\n" +
	"\n" +
	"ExportType\x12\x0f\n" +
	"\vFULL_EXPORT\x10\x00\x12\x14\n" +
	"\x10SELECTED_COLUMNS\x10\x01B:Z8gitlab.apk-group.net/siem/backend/asset-discovery/api/pbb\x06proto3"

var (
	file_export_proto_rawDescOnce sync.Once
	file_export_proto_rawDescData []byte
)

func file_export_proto_rawDescGZIP() []byte {
	file_export_proto_rawDescOnce.Do(func() {
		file_export_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_export_proto_rawDesc), len(file_export_proto_rawDesc)))
	})
	return file_export_proto_rawDescData
}

var file_export_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_export_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_export_proto_goTypes = []any{
	(ExportType)(0),              // 0: ExportType
	(*ExportAssetsRequest)(nil),  // 1: ExportAssetsRequest
	(*ExportJobDiffRequest)(nil), // 2: ExportJobDiffRequest
}
var file_export_proto_depIdxs = []int32{
	0, // 0: ExportAssetsRequest.export_type:type_name -> ExportType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_export_proto_init() }
func file_export_proto_init() {
	if File_export_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_export_proto_rawDesc), len(file_export_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_export_proto_goTypes,
		DependencyIndexes: file_export_proto_depIdxs,
		EnumInfos:         file_export_proto_enumTypes,
		MessageInfos:      file_export_proto_msgTypes,
	}.Build()
	File_export_proto = out.File
	file_export_proto_goTypes = nil
	file_export_proto_depIdxs = nil
}
