// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.6.1
// source: scanjob.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AssetScanJob struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Asset         *Asset                 `protobuf:"bytes,1,opt,name=asset,proto3" json:"asset,omitempty"`
	DiscoveredAt  string                 `protobuf:"bytes,2,opt,name=discovered_at,json=discoveredAt,proto3" json:"discovered_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssetScanJob) Reset() {
	*x = AssetScanJob{}
	mi := &file_scanjob_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssetScanJob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssetScanJob) ProtoMessage() {}

func (x *AssetScanJob) ProtoReflect() protoreflect.Message {
	mi := &file_scanjob_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssetScanJob.ProtoReflect.Descriptor instead.
func (*AssetScanJob) Descriptor() ([]byte, []int) {
	return file_scanjob_proto_rawDescGZIP(), []int{0}
}

func (x *AssetScanJob) GetAsset() *Asset {
	if x != nil {
		return x.Asset
	}
	return nil
}

func (x *AssetScanJob) GetDiscoveredAt() string {
	if x != nil {
		return x.DiscoveredAt
	}
	return ""
}

type ScanJob struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	StartTime     string                 `protobuf:"bytes,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       string                 `protobuf:"bytes,5,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Progress      int32                  `protobuf:"varint,6,opt,name=progress,proto3" json:"progress,omitempty"`
	ScannerId     int64                  `protobuf:"varint,7,opt,name=scanner_id,json=scannerId,proto3" json:"scanner_id,omitempty"`
	AssetScanJobs []*AssetScanJob        `protobuf:"bytes,8,rep,name=asset_scan_jobs,json=assetScanJobs,proto3" json:"asset_scan_jobs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanJob) Reset() {
	*x = ScanJob{}
	mi := &file_scanjob_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanJob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanJob) ProtoMessage() {}

func (x *ScanJob) ProtoReflect() protoreflect.Message {
	mi := &file_scanjob_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanJob.ProtoReflect.Descriptor instead.
func (*ScanJob) Descriptor() ([]byte, []int) {
	return file_scanjob_proto_rawDescGZIP(), []int{1}
}

func (x *ScanJob) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ScanJob) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ScanJob) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ScanJob) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *ScanJob) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *ScanJob) GetProgress() int32 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *ScanJob) GetScannerId() int64 {
	if x != nil {
		return x.ScannerId
	}
	return 0
}

func (x *ScanJob) GetAssetScanJobs() []*AssetScanJob {
	if x != nil {
		return x.AssetScanJobs
	}
	return nil
}

type ScanJobFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	StartTimeFrom string                 `protobuf:"bytes,4,opt,name=start_time_from,json=startTimeFrom,proto3" json:"start_time_from,omitempty"`
	StartTimeTo   string                 `protobuf:"bytes,5,opt,name=start_time_to,json=startTimeTo,proto3" json:"start_time_to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanJobFilter) Reset() {
	*x = ScanJobFilter{}
	mi := &file_scanjob_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanJobFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanJobFilter) ProtoMessage() {}

func (x *ScanJobFilter) ProtoReflect() protoreflect.Message {
	mi := &file_scanjob_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanJobFilter.ProtoReflect.Descriptor instead.
func (*ScanJobFilter) Descriptor() ([]byte, []int) {
	return file_scanjob_proto_rawDescGZIP(), []int{2}
}

func (x *ScanJobFilter) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ScanJobFilter) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ScanJobFilter) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ScanJobFilter) GetStartTimeFrom() string {
	if x != nil {
		return x.StartTimeFrom
	}
	return ""
}

func (x *ScanJobFilter) GetStartTimeTo() string {
	if x != nil {
		return x.StartTimeTo
	}
	return ""
}

type GetJobsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Sort          []*SortField           `protobuf:"bytes,3,rep,name=sort,proto3" json:"sort,omitempty"`
	Filter        *ScanJobFilter         `protobuf:"bytes,4,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobsRequest) Reset() {
	*x = GetJobsRequest{}
	mi := &file_scanjob_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobsRequest) ProtoMessage() {}

func (x *GetJobsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scanjob_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobsRequest.ProtoReflect.Descriptor instead.
func (*GetJobsRequest) Descriptor() ([]byte, []int) {
	return file_scanjob_proto_rawDescGZIP(), []int{3}
}

func (x *GetJobsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetJobsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetJobsRequest) GetSort() []*SortField {
	if x != nil {
		return x.Sort
	}
	return nil
}

func (x *GetJobsRequest) GetFilter() *ScanJobFilter {
	if x != nil {
		return x.Filter
	}
	return nil
}

type GetJobsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Contents      []*ScanJob             `protobuf:"bytes,1,rep,name=contents,proto3" json:"contents,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobsResponse) Reset() {
	*x = GetJobsResponse{}
	mi := &file_scanjob_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobsResponse) ProtoMessage() {}

func (x *GetJobsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scanjob_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobsResponse.ProtoReflect.Descriptor instead.
func (*GetJobsResponse) Descriptor() ([]byte, []int) {
	return file_scanjob_proto_rawDescGZIP(), []int{4}
}

func (x *GetJobsResponse) GetContents() []*ScanJob {
	if x != nil {
		return x.Contents
	}
	return nil
}

func (x *GetJobsResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type GetJobByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobByIDRequest) Reset() {
	*x = GetJobByIDRequest{}
	mi := &file_scanjob_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobByIDRequest) ProtoMessage() {}

func (x *GetJobByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scanjob_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobByIDRequest.ProtoReflect.Descriptor instead.
func (*GetJobByIDRequest) Descriptor() ([]byte, []int) {
	return file_scanjob_proto_rawDescGZIP(), []int{5}
}

func (x *GetJobByIDRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetJobByIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Job           *ScanJob               `protobuf:"bytes,1,opt,name=job,proto3" json:"job,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobByIDResponse) Reset() {
	*x = GetJobByIDResponse{}
	mi := &file_scanjob_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobByIDResponse) ProtoMessage() {}

func (x *GetJobByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scanjob_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobByIDResponse.ProtoReflect.Descriptor instead.
func (*GetJobByIDResponse) Descriptor() ([]byte, []int) {
	return file_scanjob_proto_rawDescGZIP(), []int{6}
}

func (x *GetJobByIDResponse) GetJob() *ScanJob {
	if x != nil {
		return x.Job
	}
	return nil
}

type DiffJobsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []int64                `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Sort          []*SortField           `protobuf:"bytes,5,rep,name=sort,proto3" json:"sort,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiffJobsRequest) Reset() {
	*x = DiffJobsRequest{}
	mi := &file_scanjob_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiffJobsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiffJobsRequest) ProtoMessage() {}

func (x *DiffJobsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scanjob_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiffJobsRequest.ProtoReflect.Descriptor instead.
func (*DiffJobsRequest) Descriptor() ([]byte, []int) {
	return file_scanjob_proto_rawDescGZIP(), []int{7}
}

func (x *DiffJobsRequest) GetIds() []int64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

func (x *DiffJobsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *DiffJobsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *DiffJobsRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *DiffJobsRequest) GetSort() []*SortField {
	if x != nil {
		return x.Sort
	}
	return nil
}

type DiffJobsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Contents      []*Asset               `protobuf:"bytes,1,rep,name=contents,proto3" json:"contents,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiffJobsResponse) Reset() {
	*x = DiffJobsResponse{}
	mi := &file_scanjob_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiffJobsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiffJobsResponse) ProtoMessage() {}

func (x *DiffJobsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scanjob_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiffJobsResponse.ProtoReflect.Descriptor instead.
func (*DiffJobsResponse) Descriptor() ([]byte, []int) {
	return file_scanjob_proto_rawDescGZIP(), []int{8}
}

func (x *DiffJobsResponse) GetContents() []*Asset {
	if x != nil {
		return x.Contents
	}
	return nil
}

func (x *DiffJobsResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_scanjob_proto protoreflect.FileDescriptor

const file_scanjob_proto_rawDesc = "" +
	"\n" +
	"\rscanjob.proto\x1a\vasset.proto\"Q\n" +
	"\fAssetScanJob\x12\x1c\n" +
	"\x05asset\x18\x01 \x01(\v2\x06.AssetR\x05asset\x12#\n" +
	"\rdiscovered_at\x18\x02 \x01(\tR\fdiscoveredAt\"\xf1\x01\n" +
	"\aScanJob\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"start_time\x18\x04 \x01(\tR\tstartTime\x12\x19\n" +
	"\bend_time\x18\x05 \x01(\tR\aendTime\x12\x1a\n" +
	"\bprogress\x18\x06 \x01(\x05R\bprogress\x12\x1d\n" +
	"\n" +
	"scanner_id\x18\a \x01(\x03R\tscannerId\x125\n" +
	"\x0fasset_scan_jobs\x18\b \x03(\v2\r.AssetScanJobR\rassetScanJobs\"\x9b\x01\n" +
	"\rScanJobFilter\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12&\n" +
	"\x0fstart_time_from\x18\x04 \x01(\tR\rstartTimeFrom\x12\"\n" +
	"\rstart_time_to\x18\x05 \x01(\tR\vstartTimeTo\"\x82\x01\n" +
	"\x0eGetJobsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1e\n" +
	"\x04sort\x18\x03 \x03(\v2\n" +
	".SortFieldR\x04sort\x12&\n" +
	"\x06filter\x18\x04 \x01(\v2\x0e.ScanJobFilterR\x06filter\"M\n" +
	"\x0fGetJobsResponse\x12$\n" +
	"\bcontents\x18\x01 \x03(\v2\b.ScanJobR\bcontents\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\"#\n" +
	"\x11GetJobByIDRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"0\n" +
	"\x12GetJobByIDResponse\x12\x1a\n" +
	"\x03job\x18\x01 \x01(\v2\b.ScanJobR\x03job\"\x81\x01\n" +
	"\x0fDiffJobsRequest\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\x03R\x03ids\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x1e\n" +
	"\x04sort\x18\x05 \x03(\v2\n" +
	".SortFieldR\x04sort\"L\n" +
	"\x10DiffJobsResponse\x12\"\n" +
	"\bcontents\x18\x01 \x03(\v2\x06.AssetR\bcontents\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05countB:Z8gitlab.apk-group.net/siem/backend/asset-discovery/api/pbb\x06proto3"

var (
	file_scanjob_proto_rawDescOnce sync.Once
	file_scanjob_proto_rawDescData []byte
)

func file_scanjob_proto_rawDescGZIP() []byte {
	file_scanjob_proto_rawDescOnce.Do(func() {
		file_scanjob_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_scanjob_proto_rawDesc), len(file_scanjob_proto_rawDesc)))
	})
	return file_scanjob_proto_rawDescData
}

var file_scanjob_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_scanjob_proto_goTypes = []any{
	(*AssetScanJob)(nil),       // 0: AssetScanJob
	(*ScanJob)(nil),            // 1: ScanJob
	(*ScanJobFilter)(nil),      // 2: ScanJobFilter
	(*GetJobsRequest)(nil),     // 3: GetJobsRequest
	(*GetJobsResponse)(nil),    // 4: GetJobsResponse
	(*GetJobByIDRequest)(nil),  // 5: GetJobByIDRequest
	(*GetJobByIDResponse)(nil), // 6: GetJobByIDResponse
	(*DiffJobsRequest)(nil),    // 7: DiffJobsRequest
	(*DiffJobsResponse)(nil),   // 8: DiffJobsResponse
	(*Asset)(nil),              // 9: Asset
	(*SortField)(nil),          // 10: SortField
}
var file_scanjob_proto_depIdxs = []int32{
	9,  // 0: AssetScanJob.asset:type_name -> Asset
	0,  // 1: ScanJob.asset_scan_jobs:type_name -> AssetScanJob
	10, // 2: GetJobsRequest.sort:type_name -> SortField
	2,  // 3: GetJobsRequest.filter:type_name -> ScanJobFilter
	1,  // 4: GetJobsResponse.contents:type_name -> ScanJob
	1,  // 5: GetJobByIDResponse.job:type_name -> ScanJob
	10, // 6: DiffJobsRequest.sort:type_name -> SortField
	9,  // 7: DiffJobsResponse.contents:type_name -> Asset
	8,  // [8:8] is the sub-list for method output_type
	8,  // [8:8] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_scanjob_proto_init() }
func file_scanjob_proto_init() {
	if File_scanjob_proto != nil {
		return
	}
	file_asset_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_scanjob_proto_rawDesc), len(file_scanjob_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_scanjob_proto_goTypes,
		DependencyIndexes: file_scanjob_proto_depIdxs,
		MessageInfos:      file_scanjob_proto_msgTypes,
	}.Build()
	File_scanjob_proto = out.File
	file_scanjob_proto_goTypes = nil
	file_scanjob_proto_depIdxs = nil
}
